# Game Settings Definitions
# Defines valid options, defaults, and validation rules for custom game settings

settings:
  theme:
    label: "World Theme"
    description: "The overarching theme or setting of the game world"
    default: "fantasy"
    type: "enum"
    options:
      - fantasy
      - sci-fi
      - modern
      - historical
      - post-apocalyptic
      - cyberpunk
      - steampunk
      - horror
      - mystery
      - western
      - supernatural
      - urban-fantasy
      - space-opera
      - alternate-history
    categories:
      classic: [fantasy, sci-fi, modern, historical]
      speculative: [post-apocalyptic, cyberpunk, steampunk, alternate-history]
      genre: [horror, mystery, western, supernatural]
      hybrid: [urban-fantasy, space-opera]

  genre:
    label: "Game Genre"
    description: "The primary genre or style of gameplay focus"
    default: "adventure"
    type: "enum"
    options:
      - adventure
      - mystery
      - combat
      - exploration
      - roleplay
      - survival
      - political
      - romantic
      - horror
      - comedy
      - heist
      - investigation
      - diplomacy
      - war
      - slice-of-life
    categories:
      action: [adventure, combat, survival, war]
      social: [roleplay, political, romantic, diplomacy]
      mental: [mystery, investigation, heist]
      atmospheric: [horror, comedy, slice-of-life]
      open: [exploration]

  startingLocationType:
    label: "Starting Location Type"
    description: "The type of location where adventures typically begin"
    default: "village"
    type: "enum"
    options:
      - village
      - city
      - tavern
      - wilderness
      - dungeon
      - ship
      - castle
      - monastery
      - academy
      - prison
      - spacestation
      - laboratory
      - headquarters
      - hideout
      - frontier-town
    categories:
      civilization: [village, city, tavern, castle, academy, headquarters]
      isolation: [wilderness, monastery, prison, laboratory, hideout]
      transport: [ship, spacestation]
      adventure: [dungeon, frontier-town]
    baseLevel:
      village: 1
      tavern: 1
      city: 2
      academy: 3
      castle: 4
      monastery: 2
      headquarters: 3
      wilderness: 5
      ship: 3
      spacestation: 4
      laboratory: 4
      hideout: 3
      frontier-town: 3
      dungeon: 6
      prison: 5

  magicLevel:
    label: "Magic Prevalence"
    description: "How prevalent and common magic is in the game world"
    default: "common"
    type: "enum"
    options:
      - none
      - rare
      - uncommon
      - common
      - abundant
      - omnipresent
    numericValue:
      none: 0
      rare: 1
      uncommon: 2
      common: 3
      abundant: 4
      omnipresent: 5
    descriptions:
      none: "No magic exists in this world"
      rare: "Magic is legendary and extremely uncommon"
      uncommon: "Magic exists but is unusual and noteworthy"
      common: "Magic is well-known and practiced by many"
      abundant: "Magic is commonplace in daily life"
      omnipresent: "Magic permeates every aspect of existence"

  techLevel:
    label: "Technology Level"
    description: "The technological advancement level of the world"
    default: "medieval"
    type: "enum"
    options:
      - stone-age
      - bronze-age
      - iron-age
      - medieval
      - renaissance
      - industrial
      - modern
      - near-future
      - far-future
    numericValue:
      stone-age: 1
      bronze-age: 2
      iron-age: 3
      medieval: 4
      renaissance: 5
      industrial: 6
      modern: 7
      near-future: 8
      far-future: 9
    descriptions:
      stone-age: "Primitive tools, fire, basic shelter"
      bronze-age: "Early metalworking, agriculture, writing"
      iron-age: "Advanced metallurgy, complex societies"
      medieval: "Feudalism, castles, knights, guilds"
      renaissance: "Printing, exploration, scientific method"
      industrial: "Steam power, factories, mass production"
      modern: "Electricity, automobiles, telecommunications"
      near-future: "Advanced computing, biotechnology, space travel"
      far-future: "Post-scarcity, advanced AI, interstellar civilization"

  tone:
    label: "Narrative Tone"
    description: "The overall emotional tone and atmosphere of the campaign"
    default: "heroic"
    type: "enum"
    options:
      - heroic
      - gritty
      - comedic
      - dark
      - lighthearted
      - epic
      - realistic
      - cinematic
      - surreal
      - noir
      - romantic
      - philosophical
    categories:
      optimistic: [heroic, lighthearted, comedic, romantic]
      serious: [gritty, dark, realistic, noir, philosophical]
      dramatic: [epic, cinematic]
      abstract: [surreal]
    descriptions:
      heroic: "Noble quests, clear morality, triumphant outcomes"
      gritty: "Harsh realities, moral ambiguity, tough choices"
      comedic: "Humor, satire, amusing situations and characters"
      dark: "Serious themes, high stakes, potential tragedy"
      lighthearted: "Fun adventures, minimal lasting consequences"
      epic: "Grand scope, legendary deeds, world-changing events"
      realistic: "Believable consequences, logical world behavior"
      cinematic: "Dramatic moments, visual storytelling emphasis"
      surreal: "Dream-like, abstract, reality-bending elements"
      noir: "Crime, mystery, moral ambiguity, urban setting"
      romantic: "Relationships, emotional connections, personal drama"
      philosophical: "Deep questions, ethical dilemmas, meaning of existence"

  difficulty:
    label: "Challenge Level"
    description: "The challenge level and lethality of encounters and obstacles"
    default: "normal"
    type: "enum"
    options:
      - story-mode
      - easy
      - normal
      - hard
      - extreme
      - custom
    modifiers:
      story-mode:
        deathRate: 0.0
        failureConsequences: "minimal"
        resourceScarcity: 0.5
        enemyStrength: 0.7
      easy:
        deathRate: 0.1
        failureConsequences: "light"
        resourceScarcity: 0.7
        enemyStrength: 0.8
      normal:
        deathRate: 0.3
        failureConsequences: "moderate"
        resourceScarcity: 1.0
        enemyStrength: 1.0
      hard:
        deathRate: 0.5
        failureConsequences: "severe"
        resourceScarcity: 1.3
        enemyStrength: 1.2
      extreme:
        deathRate: 0.8
        failureConsequences: "devastating"
        resourceScarcity: 1.5
        enemyStrength: 1.5
      custom:
        deathRate: "variable"
        failureConsequences: "configurable"
        resourceScarcity: "adjustable"
        enemyStrength: "customizable"

  playerStartingLevel:
    label: "Player Starting Level"
    description: "The level at which new players begin their adventure"
    default: 1
    type: "integer"
    min: 1
    max: 20
    recommendations:
      beginner: 1
      experienced: 3
      veteran: 5
      epic: 10
      legendary: 15

enabledFeatures:
  label: "Enabled Game Features"
  description: "Game systems and mechanics that are active in this setting"
  type: "array"
  default: ["combat", "magic", "exploration", "roleplay"]
  options:
    - combat
    - magic
    - exploration
    - roleplay
    - crafting
    - trading
    - politics
    - romance
    - horror
    - comedy
    - investigation
    - survival
    - naval
    - aerial
    - underground
    - planar
    - time-travel
    - dimensional
  categories:
    core: [combat, magic, exploration, roleplay]
    economic: [crafting, trading]
    social: [politics, romance]
    atmospheric: [horror, comedy]
    specialized: [investigation, survival]
    travel: [naval, aerial, underground]
    exotic: [planar, time-travel, dimensional]

customRules:
  label: "Custom Rules and Modifications"
  description: "House rules and setting-specific modifications"
  type: "object"
  default: {}
  examples:
    criticalHitRules:
      description: "Modified critical hit mechanics"
      default: "double-damage"
    magicSystem:
      description: "Alternative magic system rules"
      default: "spell-points"
    deathAndDying:
      description: "Rules for character death and revival"
      default: "standard"
    restRules:
      description: "Modified rest and recovery mechanics"
      default: "long-rest-week"

metadata:
  version: "1.0.0"
  lastUpdated: "2025-09-14"
  compatibility:
    gameVersion: ">=1.0.0"
    templateVersion: ">=2.0.0"
  tags:
    - "core-settings"
    - "world-building"
    - "game-configuration"
