# AI RPG Configuration Template
# Copy this file to config.yaml and update with your settings

server:
  port: 7777
  host: 0.0.0.0 # Use localhost for local development, 0.0.0.0 for external access

max_memories_to_recall: 10

# OpenAI-compatible API configuration
ai:
  # API endpoint URL (examples):
  # OpenAI: "https://api.openai.com/v1"
  # LocalAI: "http://localhost:8080/v1"
  # Ollama: "http://localhost:11434/v1"
  # nano-gpt: "https://nano-gpt.com/api/v1"
  endpoint: "https://nano-gpt.com/api/v1"

  # Your API key (keep this secure!)
  apiKey: "your-api-key-here"

  # Model to use (examples):
  # OpenAI: "gpt-3.5-turbo", "gpt-4"
  # LocalAI: depends on your models
  # Ollama: "llama2", "mistral", etc.
  model: "zai-org/GLM-4.5-FP8"

  # Optional: Additional parameters
  maxTokens: 2000
  temperature: 0.7
  baseTimeoutSeconds: 120

model_swap_options:
  - "zai-org/GLM-4.5-FP8"
  - "gpt-4o-mini"

imagegen:
  enabled: true
  # engine can currently be "comfyui", "nanogpt", or "openai"
  engine: nanogpt

  # api_template is still used to build comfyui prompts and can be ignored for others. Uncomment one of the below lines as needed.
  #api_template: sdxl_illustrious.json.njk
  api_template: qwen_image.json.njk

  # Checkpoint is relative to the ComfyUI models/
  # Required for ComfyUI engine
  #checkpoint: "sdxl/QuillworksIllustrious_QuillworksV15.safetensors"
  #server:
  #host: localhost
  #port: 8188

  # When engine is "nanogpt" or "openai", the following fields are required:
  # api_template is still used to build prompts
  # model: model name from your image generation host
  # endpoint: "https://..." (leave blank for the engine's default hosted endpoint)
  # apiKey: "..."
  apiKey: "YOUR API KEY HERE"
  endpoint:
  model: "qwen-image"

  # For Illustrious or SDXL based models, you might want to use these templates (regardless of engine):
  #prompt_generator_templates:
  #character: player-portrait-illustrious.xml.njk
  #item: item-image-illustrious.xml.njk
  #location: location-image-illustrious.xml.njk
  #scenery: scenery-image-illustrious.xml.njk
  # For running qwen-image or similar models, you might want to use these templates (regardless of engine):
  prompt_generator_templates:
    character: player-portrait.xml.njk
    item: item-image.xml.njk
    location: location-image.xml.njk
    scenery: scenery-image.xml.njk
  default_negative_prompt: indistinct, poor quality, blurry, low detail

  # This only matters for prompt templates that use {{ megapixels }}.
  # It is used to scale width/height in templates that use hires fix.
  megapixels: 1.0

  default_settings:
    image:
      width: 1024
      height: 1024
      seed: 42
  location_settings:
    image:
      width: 1280
      height: 720
random_event_frequency:
  common: 0.04
  rare: 0.01
# Game Master configuration
gamemaster:
  # Fallback system prompt
  promptTemplate: "gamemaster.njk"
regions:
  minLocations: 2
  maxLocations: 3
locations:
  maxNpcs: 4
  maxHostiles: 4
  maxItems: 4
  maxScenery: 4
  levelVariation: 3

# Number of events to check concurrently when processing text. Omit to do them all.
# A lower number makes it easier for the AI but is slower and will use more tokens/requests.
# You can omit this for sophisticated models that can handle more complex prompts.
events_to_check_concurrently: 10

# This can be: never, unexplored_regions, unexplored_locations, or always
check_move_plausibility: unexplored_locations

# Jailbreak? Put it here.
# extra_system_instructions:

# Mostly to speed up testing and development - prevent certain types of generation
omit_npc_generation: false
omit_item_generation: false
deduplicate_item_names: true
summaries:
  enabled: true
  summarize_on_load: false
  batch_size: 30
  summary_word_length: 12
  max_unsummarized_log_entries: 100
party_generate_memory_interval: 25
